### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ghost** [datto/php-json-rpc#8] opened 2018-08-28 09:04 UTC
`composer require "datto/json-rpc" "~5.0"`

I used the examples in the vendor folder which were installed by this command.

It's not working at all.

I spent few hours and tried below.
`git clone https://github.com/datto/php-json-rpc.git`
`cd php-json-rpc-http`
`composer install`

And used the commands in this document(https://github.com/datto/php-json-rpc-http/tree/master/examples/authenticated#run-the-examples)

Then it works.

Why don't you edit your installation part?

------------------------------------------------------------
I have a question.

```
// Construct a client that can query your remote server over HTTP(S):
$client = new Client($url, $username, $password);

// Add the numbers "1" and "2":
$client->query(1, 'add', array(1, 2));
```

What means 1 in the first argument?

I'm trying to another server. but I don't know what it is.

**Comment by spencer-mortensen** [comment] 2018-08-28 22:33
Hmm... I'm not able to reproduce your report. But the client and server examples are working.

But! Your sample commands switch from the "php-json-rpc" project to a different project ("php-json-rpc-http") midway through: Could that have been a problem?

The first argument (the "1" in the example) is an id that you can choose freely. When the server responds, the response will contain your id. This allows you to match up the response with your original request.

The JSON-RPC website has a great explanation of a request and a response:
https://www.jsonrpc.org/specification

It could be technical, but it's super useful.

**Comment by smortensen** [comment] 2018-08-30 03:40
I hope you've figured out the JSON-RPC parts, and I hope things are going all right with your project.

I'm going to close this bug report, since the examples are working.

Let me know if there's anything I can do for you.

**Closed as completed by smortensen** 2018-08-30 03:40 UTC
